apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-deployment
spec:
  replicas: 1  # Number of replicas (pods) for high availability
  selector:
    matchLabels:
      app: oxygen-app
  template:
    metadata:
      labels:
        app: oxygen-app
    spec:
      containers:
        - name: oxygen-container
          image: samkryszto/oxygen:latest
          env:
            - name: TOKEN
              value: ${{ secrets.TOKEN }}
            - name: DATABASE
              value: ${{ secrets.DATABASE }}
            - name: HOST
              value: ${{ secrets.HOST }}
            - name: TICKETS
              value: ${{ secrets.TICKETS }}
            - name: T_MIN
              value: ${{ secrets.T_MIN }}
            - name: T_MAX
              value: ${{ secrets.T_MAX }}
          ports:
            - containerPort: 8000  # Replace with your application's exposed port
      # Add other specifications like volumes, resource limits, etc. if needed


apiVersion: apps/v1
kind: Service
metadata:
  name: oxygen-service
spec:
  selector:
    app: oxygen-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
