# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-deployment
spec:
              replicas: 3
              selector:
                matchLabels:
                  app: oxygen-app
              template:
                metadata:
                  labels:
                    app: oxygen-app
                spec:
                  containers:
                    - name: oxygen-container
                      image: samkryszto/oxygen:latest
                      ports:
                        - containerPort: 8000
                      # Add other container configuration as needed
