apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-deployment
spec:
  replicas: 3  # Number of replicas (pods) for high availability
  selector:
    matchLabels:
      app: oxygen-app
  template:
    metadata:
      labels:
        app: oxygen-app
    spec:
      containers:
        - name: oxygen-container
          image: samkryszto/oxygen:latest
          env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: token
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: database
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: host
          - name: TICKETS
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: tickets
          - name: T_MIN
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: t-min
          - name: T_MAX
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: t-max
          ports:
            - containerPort: 8000  # /Replace with your application's exposed port
          resources:
            limits:
              cpu: "500m"  # CPU limit set to 500 milliCPU
              memory: "500Mi"  # Memory limit set to 500 MiB
            requests:
              cpu: "100m"  # Minimum CPU request set to 100 milliCPU
              memory: "100Mi"  # Minimum memory request set to 100 MiB
