apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-deployment
spec:
  replicas: 1  # Number of replicas (pods) for high availability
  selector:
    matchLabels:
      app: oxygen-app
  template:
    metadata:
      labels:
        app: oxygen-app
    spec:
      containers:
        - name: oxygen-container
          image: samkryszto/oxygen:latest
          env:
            - name: TOKEN
              value: ${TOKEN}
            - name: DATABASE
              value: ${DATABASE}
            - name: HOST
              value: ${HOST}
            - name: TICKETS
              value: ${TICKETS}
            - name: T_MIN
              value: ${T_MIN}
            - name: T_MAX
              value: ${T_MAX}
          ports:
            - containerPort: 8000  # /Replace with your application's exposed port
          resources:
            limits:
              cpu: "500m"  # CPU limit set to 500 milliCPU
              memory: "500Mi"  # Memory limit set to 500 MiB
            requests:
              cpu: "100m"  # Minimum CPU request set to 100 milliCPU
              memory: "100Mi"  # Minimum memory request set to 100 MiB
