apiVersion: apps/v1
kind: Service
metadata:
  name: oxygen-service
spec:
  selector:
    app.kubernetes.io/name: oxygen-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
