version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Upgrade pip
          command: |
            pip install --upgrade pip

      - run:
          name: Clean up containers and images
          command: |
            docker-compose down --volumes --remove-orphans
            docker system prune --all --force --volumes

      - run:
          name: Use secret TOKEN
          command: echo $TOKEN
          environment:
            TOKEN: ${{ secrets.TOKEN }}
          when: on_success

      - run:
          name: Use secret T_MAX
          command: echo $T_MAX
          environment:
            T_MAX: ${{ secrets.T_MAX }}
          when: on_success

      - run:
          name: Use secret T_MIN
          command: echo $T_MIN
          environment:
            T_MIN: ${{ secrets.T_MIN }}
          when: on_success

      - run:
          name: Use secret HOST
          command: echo $HOST
          environment:
            HOST: ${{ secrets.HOST }}
          when: on_success

      - run:
          name: Use secret DATABASE
          command: echo $DATABASE
          environment:
            DATABASE: ${{ secrets.DATABASE }}
          when: on_success

      - run:
          name: Create network
          command: docker network create postgres_network
      - run:
          name: Check if TOKEN is set
          command: |
            if [ -z "$TOKEN" ]; then
              echo "ERROR: TOKEN environment variable is not set."
              exit 1
            else
              echo "TOKEN is set: $TOKEN"
            fi
          
      - run:
          name: Build container
          command: docker-compose build
          environment:
              TOKEN: ${{ secrets.TOKEN }}
              DATABASE: ${{ secrets.DATABASE }}
              HOST: ${{ secrets.HOST }}
              TICKETS: ${{ secrets.TICKETS }}
              T_MIN: ${{ secrets.T_MIN }}
              T_MAX: ${{ secrets.T_MAX }}
          when: on_success

      - run:
          name: Install dependencies
          command: |
            docker-compose run --rm app pipenv install --dev
          when: on_success

      - run:
          name: Run tests
          command: |
            docker-compose run --rm app pipenv run pytest
          environment:
            TOKEN: ${{ secrets.TOKEN }}
            DATABASE: ${{ secrets.DATABASE }}
            HOST: ${{ secrets.HOST }}
            TICKETS: ${{ secrets.TICKETS }}
            T_MIN: ${{ secrets.T_MIN }}
            T_MAX: ${{ secrets.T_MAX }}
          when: on_success

      - run:
          name: Stop container if tests fail
          command: docker-compose down
          when: on_fail

      - run:
          name: Install pylint and black
          command: |
            pip install pylint black

      - run:
          name: Run pylint and black
          command: |
            pylint src --rcfile=.pylintrc
            black src --check
          when: on_success

      - run:
          name: Execute main.py
          command: docker-compose run --rm app pipenv run start
          when: on_success

      - run:
          name: Use secret
          command: echo $DOCKERHUB_ID
          environment:
            MY_SECRET_VARIABLE: ${{ secrets.DOCKERHUB_ID }}
          when: on_success

      - run:
          name: Use secret
          command: echo $DOCKERHUB_PWD
          environment:
            MY_SECRET_VARIABLE: ${{ secrets.DOCKERHUB_PWD }}
          when: on_success

      - run:
          name: Deploy to Docker Hub
          command: |
            echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_ID" --password-stdin
            # Define the repository name and tag
            oxygen_repo="samkryszto/oxygen"
            oxygen_tag="latest"

            # Get the image ID for the service
            image_id=$(docker-compose images -q)
             # Get the build number
            build_number=${CIRCLE_BUILD_NUM:-local}

            # Tag the image with the repository and tag
            if [ "$build_number" = "local" ]; then
              # Use "latest" tag for local builds
              docker tag $image_id $oxygen_repo:latest
            else
              # Use build number as the tag for non-local builds
              docker tag $image_id $oxygen_repo:$build_number
              docker tag $image_id $oxygen_repo:latest
            fi
            # Tag the image with the repository and tag
            docker tag $image_id $oxygen_repo:$oxygen_tag

            # Push the tagged image to Docker Hub
            docker push $oxygen_repo:$oxygen_tag
          when: on_success

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: circleci-project-setup
